#include "fs.h"

struct fsdata_file {
    struct fsdata_file const *next;
    unsigned char const *name;
    unsigned char const *data;
    int const len;
};

#include "fsdata.h"   /* file-system data generated by qfsgen utility */

#include <string.h>


int fs_get(char const *name, char const **data, int *len)
{
    const struct fsdata_file *f;
    int retcode = FS_NOT_FOUND;

    for (f = FS_ROOT; f != NULL; f = f->next) {
        if (!strcmp(name, (char const *)f->name)) {
        	*data = (char const *)f->data;
        	*len = f->len;
        	retcode = FS_FOUND;
        	break;
        }
    }
    return retcode;
}


char const *fs_type(char const *name)
{
	char const *s;
	char const *ret;

    s = strrchr(name, '.');
      if (s != 0) { // '.' found?
          if ((strcmp(s, ".htm") == 0)
              || (strcmp(s, ".html") == 0)) /* .htm/.html files */
          {
              ret = "text/html";
          }
          else if ((strcmp(s, ".shtm") == 0)
                   || (strcmp(s, ".shtml") == 0)) /* .shtm/.shtml files */
          {
              ret = "text/html";
          }
          else if (strcmp(s, ".css") == 0) {
              ret = "text/css";
          }
          else if (strcmp(s, ".js") == 0) {
              ret = "application/javascript";
          }
          else if (strcmp(s, ".json") == 0) {
              ret = "application/json";
          }
          else if (strcmp(s, ".gif") == 0) {
              ret = "image/gif";
          }
          else if (strcmp(s, ".png") == 0) {
              ret = "image/png";
          }
          else if (strcmp(s, ".jpg") == 0) {
        	  ret = "image/jpeg";
          }
          else if (strcmp(s, ".bmp") == 0) {
              ret = "image/bmp";
          }
          else if (strcmp(s, ".ico") == 0) {
              ret = "image/x-icon";
          }
          else if (strcmp(s, ".class") == 0) {
        	  ret = "application/octet-stream";
          }
          else if (strcmp(s, ".ram") == 0) {
        	  ret = "audio/x-pn-realaudio";
          }
          else {
        	  ret = "text/plain";
          }
      }
      else {
    	  ret = "text/plain";
      }

      return ret;
}

