#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ntp_clock

EXCLUDE_COMPONENTS=coap jsmn libsodium mqtt

# configure static allocation and max priorities for qpc

include $(IDF_PATH)/make/project.mk

