/*$file${../project/compo~::myao.c} ########################################*/
/*
* Model: ntp_clock.qm
* File:  ${../project/compo~::myao.c}
*
* This code has been generated by QM 4.3.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${../project/compo~::myao.c} #####################################*/
#include "qpc.h"
#include "project.h"

/* Check for the minimum required QP version */
#if (QP_VERSION < 630U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.3.0 or higher required
#endif

/*$define${AOs::MyAO} ######################################################*/
/*${AOs::MyAO} .............................................................*/
/*${AOs::MyAO::ctor} .......................................................*/
void MyAO_ctor(MyAO * const me) {
    QActive_ctor(&me->super, Q_STATE_CAST(&MyAO_initial));
}

/*${AOs::MyAO::SM} .........................................................*/
QState MyAO_initial(MyAO * const me, QEvt const * const e) {
    /*${AOs::MyAO::SM::initial} */
    return Q_TRAN(&MyAO_state1);
}
/*${AOs::MyAO::SM::state1} .................................................*/
QState MyAO_state1(MyAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::MyAO} ######################################################*/

/* define other elements... */