/*$file${../project/compo~::project.h} #####################################*/
/*
* Model: ntp_clock.qm
* File:  ${../project/compo~::project.h}
*
* This code has been generated by QM 4.3.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${../project/compo~::project.h} ##################################*/
#ifndef project_h
#define project_h

/* define the event signals used in the application ------------------------*/
enum ProjectSignals {
    MAX_PUB_SIG  = Q_USER_SIG,   /* we can't use publish-subscribe machanism */
    BUTTON_SIG,
    TIMEOUT_SIG,
    MAX_SIG                     /* the last signal */
};

/*$declare${Events} ########################################################*/

/* example event object */
/*${Events::MyEvt} .........................................................*/
typedef struct {
/* protected: */
    QEvt super;
} MyEvt;

/* second example */
/*${Events::Class1} ........................................................*/
typedef struct {
/* protected: */
    QEvt super;
} Class1;
/*$enddecl${Events} ########################################################*/

/*$declare${AOs::theClock} #################################################*/

/*pointer to static instance of the Clock */
extern QHsm * const theClock;
/*$enddecl${AOs::theClock} #################################################*/

/*$declare${AOs::Clock_ctor} ###############################################*/

/*Clock constructor */
/*${AOs::Clock_ctor} .......................................................*/
void Clock_ctor(void);
/*$enddecl${AOs::Clock_ctor} ###############################################*/

/* declare other elements... */

#endif /* project_h */